version: '3'

services:
  web-prod:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '8000:8000'
    depends_on:
      - ws-prod

  ws-prod:
    build:
      context: .
      dockerfile: packages/ws/Dockerfile
    environment:
      - NODE_ENV=development
